---
language: bash

# Tell Travis to start Docker when it brings up an environment.
services:
  - docker

env:
  global:
    - DOCKER_REPO=turgon37/transmission
    - secure: 'LRpfmKFY9pBD35dHl1bKscXojV3albq+TZfbBJDMcTHwbyJ4s9JklHIS525ZZWxwu8EITKfr9NFV0WuBDKMMvcjGgWTs6GDIXcKREJL28RhKN6rmC5CpMILv9tIZpKThDqbT3T6ScfXE4g2XAvMT43S/2wQ1dt5pUryWIq8Nx4YXNnUgobt9UNqXuRoAPWmviiycUvxDaUD4gixJfDLp7IvGwSqqu7ZUCPlGKMiaMxAwvSlfKMJG3Fyq4vdgeltpPN1RC9XVUKs9ac55lpWcrFm3mCs+aVAe+fpaXzIOlBlmW0W8xXs0Q4u4v5SAuyimMcjbC05KyaRsA+8jGGcKeTcsFjIVtJOUKShdmxdtuobNuDr06fXXHgKdg08XeayDbbaikODgPBbTR+VDTXUBBnWx/GM18B0M925CoXSRN4Oy2HPqOBEnprKGz1LlsOfX2OHpjY/dbLsStZ48Jf05u7K9xqwVEXRnTy2LnURNpub+4hg042amizhF7oSxuSMDP/eItpnIn3MI3z6UgDbBJF5cmh4renclPTsKnljiOkmxILgowDhPpJHXzknEuiG3HHbtT5i306bQHj8fEBmaWioCMU7v7UtulTWbzsHGfkpBrWhfHI/61DW/iofGaQ7kmHjXbOosPZUVSo+GJEaoqHCaLO314Z3SFDmZFPYN1+Y='
    - secure: 'Z7PBzC4Uq68UOYG5NyTGfeRn9exbFzw9CyH9uN83FvhdlXLVpiQMqeFj3ZBj4jzBXenb9SheKeD2KSOe5CB8wkhEcKySTq6MgluzXspF3DbBvua+aOA5PXg/o6EoQMWV8egevL1yy7qQHhrg3AkeHMD7BQIPDwAH7d8DTettPvzHEkJr5r44IEIF/2c29SLUxh7LQo5PLU+jOSbtZmpOVYDHgNtM1kgBoy14QDyFGkIZk2ACgTLVFH6G8eD8zjNAnnsLRIKXU5NQzJjR9AlJPzvr7/V6PVya9of3GMYCyEURY2jvLvnYDdJZYiwnnLWd7qmA5fvCwExaLNiB2FDk8AoB84sDiNJPD/BNFeCoWrC9PNQB0bJanibtzQWEF1l4dygLyxdh5DGFDx7Hp2p2q1UPOnw5DCCbDutd4+QdQGtxwFIAIk6UBWz/TFW2kyio4FuGPMVjqkKsvuccnclNJCetW+OqtHUc7u4qBvNRW4vFf9imgmm3/QoP+2qwooOkadvKOfaFlC4Hx81a4IxJFDVT6xMsiY0vMm9Bj6EkzSDmtRkGhxNVc+u+nuRdKMsQ6xf7Gvg/jUNLFURqqNBXeZ5c5sjCXtCs/hZHdkO+w1v/WPQsPrpRFdh6oMY/AKEvr2O+YVDk/9LRMryg+r93lV2ArRCUSB5BXMpvQ20M/fk='
  matrix:
    # Provide a list of transmission version to build
    - TRANSMISSION_VERSION=""

script:
  #
  ## Build
  #
  - ./build.sh

  #
  ## Run tests
  #
  - ./tests.sh && touch _test_ok

  #
  ## Publish
  #
  - '[ "$TRAVIS_PULL_REQUEST" == "false" ] || exit 0'
  - '[ "$TRAVIS_SECURE_ENV_VARS" == "true" -a -f _test_ok ] && ./publish.sh'
